spring:
 cloud:
   gateway:
     routes:
       - id: marketing-service
         uri: http://localhost:8083
         predicates:
           - Path=/marketing/**
         filters:
           - AuthFilter


       - id: customer-service
         uri: http://localhost:8082
         predicates:
           - Path=/customers/**
         filters:
           - AuthFilter

       - id: auth-service
         uri: http://localhost:8081
         predicates:
           - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/